#ifndef PKGINTEL_VERSION_H
#define PKGINTEL_VERSION_H
#define PKGINTEL_VERSION_MAJOR 0
#define PKGINTEL_VERSION_MINOR 1
#define PKGINTEL_VERSION_PATCH 0
#define PKGINTEL_API_MAJOR 0
#define PKGINTEL_API_MINOR 1
#endif
